apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: enterprise-app-pipeline
spec:
  params:
    - name: IMAGE_REPO
      type: string
      default: image-registry.openshift-image-registry.svc:5000/enterprise-app-dev/enterprise-app
    - name: IMAGE_TAG
      type: string
      default: latest
    - name: MANIFEST_FILE
      type: string
      default: components/apps/enterprise-app/overlays/dev/kustomization.yaml
    - name: COMMIT_AUTHOR
      type: string
      default: tekton    
    - name: MANIFEST_REPO
      type: string
      default: https://github.com/sumiranchugh/enterprise-app-gitops.git       
    - name: GIT_REPO
      type: string
      default: https://github.com/sumiranchugh/enterprise-app.git
    - name: GIT_REVISION
      type: string
      default: main
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: main
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_REPO):latest
        - name: TLSVERIFY
          value: 'false'
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-php
      workspaces:
        - name: source
          workspace: workspace          
    - name: deploy
      params:
        - name: image
          value: $(params.IMAGE_REPO):$(params.IMAGE_TAG)
        - name: configuration_file
          value: $(params.MANIFEST_FILE)
        - name: repository
          value: $(params.MANIFEST_REPO)
        - name: git_user_name
          value: $(params.COMMIT_AUTHOR)
      runAfter:
        - build
      taskRef:
        kind: Task
        name: update-manifest
  workspaces:
    - name: workspace
      
  