kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    app.openshift.io/connects-to: debezium
  name: mssql-server-linux
  labels:
    app: mssql-server-linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-server-linux
  template:
    metadata:
      labels:
        app: mssql-server-linux
        deploymentconfig: mssql-server-linux
    spec:
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: mssql-server-volume
        - name: data-sql
          configMap:
            name: data-sql
            defaultMode: 420
      containers:
        - resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 3Gi
          terminationMessagePath: /dev/termination-log
          name: mssql-server-linux
          env:
            - name: ACCEPT_EULA
              value: 'Y'
            - name: SA_PASSWORD
              value: Password!
            - name: MSSQL_PID
              value: Standard
            - name: MSSQL_AGENT_ENABLED
              value: 'true'
          ports:
            - containerPort: 1433
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: db-data
              mountPath: /var/opt/mssql
            - name: data-sql
              mountPath: /opt/workshop
          terminationMessagePolicy: File
          image: >-
            mcr.microsoft.com/mssql/server@sha256:6ad336d284ec3b20d5ee89d68be03bce7b8018904e798a5d4bddcadc298dbd54
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
