apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: git-event-listener-interceptor
  name: git-event-listener-el
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-git-event-listener-interceptor