apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: git-event-listener
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: enterprise-push-binding
    template:
      ref: enterprise-ci-template