apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: enterprise-ci-template
  labels: 
    tekton.dev/pipeline: enterprise-app-pipeline
spec:
  params:
  - description: The git branch for this PR.
    name: commitRef
  - description: the specific commit SHA.
    name: commitId
  - description: the specific short commit SHA.
    name: commitIdShort
  - description: The date at which the commit was made
    name: commitDate
  - description: The name of the github user handle that made the commit
    name: commitAuthor
  - description: The commit message
    name: commitMessage
  - description: The git repository URL.
    name: gitRepositoryUrl
  - description: The git revision.
    name: gitRevision  
  - description: The repository name for this PullRequest.
    name: repositoryFullname
  - description: The repository to push built images to.
    name: imageRepo
  - description: The file to update to point to newly built image
    name: manifestFile
  - description: The git repository server with the manifest files
    name: manifestRepoGitServer
  - description: The secret with the git token
    name: manifestGitTokenSecretName
  - description: The full name of the manifest repository
    name: manifestRepoFullName
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: enterprise-ci-run-$(uid)
      labels: 
        tekton.dev/pipeline: enterprise-app-pipeline
    spec:
      params:
      - name: GIT_REPO
        value: $(tt.params.gitRepositoryUrl)
      - name: GIT_REVISION
        value: $(tt.params.gitRevision)  
      - name: GIT_REF
        value: $(tt.params.commitRef)
      - name: IMAGE_REPO
        value: $(tt.params.imageRepo)
      - name: IMAGE_TAG
        value: $(tt.params.commitId)
      - name: MANIFEST_REPO
        value: $(tt.params.manifestRepoGitServer)/$(tt.params.manifestRepoFullName).git
      - name: MANIFEST_FILE
        value: $(tt.params.manifestFile)  
      - name: COMMIT_MESSAGE
        value: $(tt.params.commitMessage)
      - name: COMMIT_AUTHOR
        value: $(tt.params.commitAuthor)
      - name: COMMIT_DATE
        value: $(tt.params.commitDate)
      - name: COMMIT_SHA
        value: $(tt.params.commitId)
      pipelineRef:
        name: enterprise-app-pipeline
      serviceAccountName: pipeline
      timeout: "1h0m0s"
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: workspace
      - name: ephemeral
        emptyDir: {}    
