apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: enterprise-push-binding
  labels: 
    tekton.dev/pipeline: enterprise-app-pipeline
spec:
  params:
  - name: IMAGE_REPO
    value: image-registry.openshift-image-registry.svc:5000/enterprise-app-dev/enterprise-app
  - name: IMAGE_TAG
    value: $(body.head_commit.id)  
  - name: gitRepositoryUrl
    value: $(body.repository.clone_url)
  - name: gitRevision
    value: $(body.ref)  
  - name: repositoryFullname
    value: $(body.repository.full_name)
  - name: commitId
    value: $(body.head_commit.id)
  - name: commitDate
    value: $(body.head_commit.timestamp)
  - name: COMMIT_AUTHOR
    value: $(body.head_commit.author.name)
  - name: manifestRepoGitServer
    value: "https://github.com/sumiranchugh"
  - name: manifestGitTokenSecretName
    value: enterprise-gitops-repo
  - name: manifestRepoFullName
    value: "enterprise-app-gitops"
  - name: manifestFile
    value: components/apps/enterprise-app/overlays/dev/kustomization.yaml
  - name: imageRepo
    value: 'image-registry.openshift-image-registry.svc:5000/enterprise-app-dev/enterprise-app'    
  
