kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace
  namespace: enterprise-app-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
