apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: earth-cluster
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: internal
        port: 9093
        tls: true
        type: route
    replicas: 3
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 2Gi
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
    storage:
      type: ephemeral
