apiVersion: v1
kind: Secret
metadata:
  name: image-registry-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LXo4bnhrLmFwcHMuY2x1c3Rlci16OG54ay5zYW5kYm94MTk2Ny5vcGVudGxjLmNvbSI6IHsKICAgICAgImF1dGgiOiAiWVdSdGFXNHJjR2x3Wld4cGJtVTZTVWcyTXpKUFNFaElVVGN5TlZBd1JGcEJVVTA0VTBkVVEwMVRURVJSUVRrMU5VeElSMHhZU1VWRFVqSk9VVXBIU2poSFJVcEdNMDVGVGpKV05sZFNXZz09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson