apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: enterprise-push-binding
spec:
  params:
  - name: gitRepositoryUrl
    value: $(body.repository.clone_url)
  - name: repositoryFullname
    value: $(body.repository.full_name)
  - name: commitRef
    value: $(extensions.ref)
  - name: commitId
    value: $(body.head_commit.id)
  - name: commitIdShort
    value: $(extensions.commit-id-short)
  - name: commitDate
    value: $(body.head_commit.timestamp)
  - name: commitMessage
    value: $(extensions.commit-message-fix-newline)
  - name: commitAuthor
    value: $(body.head_commit.author.name)
  - name: dockerFile
    value: "./.docker/Dockerfile"
  - name: imageRepo
    value: quay-z8nxk.apps.cluster-z8nxk.sandbox1967.opentlc.com/admin/gitops
  - name: manifestRepoGitServer
    value: "https://github.com"
  - name: manifestGitTokenSecretName
    value: enterprise-gitops-repo
  - name: manifestGitTokenSecretKey
    value: token
  - name: manifestGitApiHost
    value: api.github.com
  - name: manifestRepoFullName
    value: "enterprise-app-gitops"
  - name: manifestGitApiPathPrefix
    value: ""
  - name: manifestGitAuthType
    value: token
  